remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Yuxin Wu
logo: assets/imgs/otto.png
description: Computer Science Phd Student at Emory Univerisy Georgia Aquarium Campus
github:
  is_user_page: false
google_analytics:
